import random
import discord
from discord.ext import commands

async def color_command(ctx):
    # Generate random RGB values
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)

    # Color conversions
    hex_color = f'#{r:02x}{g:02x}{b:02x}'
    rgb_color = (r, g, b)
    rgb_decimal = r * 65536 + g * 256 + b
    hsl_color = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
    hsv_color = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)

    # Create an embed
    embed = discord.Embed(title='Random Color', color=discord.Color.from_rgb(r, g, b))
    embed.add_field(name='Hex', value=hex_color, inline=True)
    embed.add_field(name='RGB', value=f'{r}, {g}, {b}', inline=True)
    embed.add_field(name='RGB Decimal', value=rgb_decimal, inline=True)
    embed.add_field(name='HSL', value=f'{hsl_color[0]:.2f}, {hsl_color[1]:.2f}, {hsl_color[2]:.2f}', inline=True)
    embed.add_field(name='HSV', value=f'{hsv_color[0]:.2f}, {hsv_color[1]:.2f}, {hsv_color[2]:.2f}', inline=True)
    embed.set_footer(text='Generated by the color command')
    await ctx.send(embed=embed)
